apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: z8dq5d2dz-python 
  janus-idp.io/tekton: z8dq5d2dz-python
  backstage.io/kubernetes-id: z8dq5d2dz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z8dq5d2dz-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml